In [13]:
import pandas as pd
from datetime import datetime, timedelta
from dateutil.relativedelta import relativedelta

# Load the Excel file
file_path = r"C:\Users\Denve\Desktop\Pk\Beer\SCMSample (1).xlsx"
df = pd.read_excel(file_path)

# Generate entries for the last 6 months
all_data = []

start_date = datetime(2024, 4, 1)
end_date = datetime(2024,7,31)
date_range = pd.date_range(start=start_date, end=end_date)



for date in date_range:
    new_df = df.copy()
    new_df['Sale Date'] = date.strftime('%m/%d/%Y') 
    all_data.append(new_df)

# Combine original data with new data
combined_df = pd.concat(all_data, ignore_index=True)

# Save to a new Excel file
output_path = r"C:\Users\Denve\Downloads\SCMSFinalBar_1.xlsx"
combined_df.to_excel(output_path, index=False)
print(f"Updated file saved at: {output_path}")

Updated file saved at: C:\Users\Denve\Downloads\SCMSFinalBar_1.xlsx

In [7]:
import pandas as pd
from datetime import datetime

# Load the dataset
file_path = r"C:\Users\Denve\Desktop\Pk\SCMSFinalBar1111.xlsx"  # Replace with your file path
df = pd.read_excel(file_path)

# Ensure the Date column is in datetime format
df['Sale Date'] = pd.to_datetime(df['Sale Date'], format="%m/%d/%Y")

# Extract the month and year for grouping
df['Month_Year'] = df['Sale Date'].dt.strftime('%B_%Y')  # Example: January_2025

# Group by Month_Year and save each group to a new Excel file
for month_year, group in df.groupby('Month_Year'):
    output_file = fr"C:\Users\Denve\Desktop\Pk\beer\{month_year}.xlsx"
    group['Sale Date'] = group['Sale Date'].dt.strftime("%m/%d/%Y")
    group.drop(columns=['Month_Year'], inplace=True)
    group.to_excel(output_file, index=False)
    print(f"File saved: {output_file}")

File saved: C:\Users\Denve\Desktop\Pk\beer\April_2024.xlsx
File saved: C:\Users\Denve\Desktop\Pk\beer\August_2024.xlsx
File saved: C:\Users\Denve\Desktop\Pk\beer\December_2024.xlsx
File saved: C:\Users\Denve\Desktop\Pk\beer\January_2025.xlsx
File saved: C:\Users\Denve\Desktop\Pk\beer\July_2024.xlsx
File saved: C:\Users\Denve\Desktop\Pk\beer\June_2024.xlsx
File saved: C:\Users\Denve\Desktop\Pk\beer\May_2024.xlsx
File saved: C:\Users\Denve\Desktop\Pk\beer\November_2024.xlsx
File saved: C:\Users\Denve\Desktop\Pk\beer\October_2024.xlsx
File saved: C:\Users\Denve\Desktop\Pk\beer\September_2024.xlsx

In [11]:
import re
import openpyxl

# Input log string

text_file_path = r"C:\Users\Denve\Desktop\Pk\temp.txt"

with open(text_file_path, 'r') as file:
    log_value = file.read().strip()




log = log_value.split("\n")
# Extract the row number using regex

file_path = r"C:\Users\Denve\Desktop\Pk\Beer\July_2024.xlsx"  # Replace with your file's path
wb = openpyxl.load_workbook(file_path)
sheet = wb.active  # Assuming the data is in the active sheet

for log_text in log:
    match = re.search(r"Row No:\((\d+)\)", log_text)
    if match:
        row_number = int(match.group(1))
    else:
        print("Row number not found in the log text.")
        exit()

    # Open the Excel file

    # Check if the row exists and delete it
    if row_number <= sheet.max_row:
        sheet.cell(row=row_number+1, column=6, value="")
        print(f"Row {row_number} deleted successfully.")

# Save the updated Excel file
wb.save(file_path)
print("File updated successfully.")

Row 33 deleted successfully.
Row 259 deleted successfully.
Row 296 deleted successfully.
Row 325 deleted successfully.
Row 442 deleted successfully.
Row 471 deleted successfully.
Row 472 deleted successfully.
Row 520 deleted successfully.
Row 588 deleted successfully.
Row 610 deleted successfully.
Row 617 deleted successfully.
Row 618 deleted successfully.
Row 677 deleted successfully.
Row 734 deleted successfully.
Row 763 deleted successfully.
Row 764 deleted successfully.
Row 880 deleted successfully.
Row 909 deleted successfully.
Row 910 deleted successfully.
Row 1023 deleted successfully.
Row 1104 deleted successfully.
Row 1172 deleted successfully.
Row 1201 deleted successfully.
Row 1202 deleted successfully.
Row 1318 deleted successfully.
Row 1347 deleted successfully.
Row 1348 deleted successfully.
Row 1464 deleted successfully.
Row 1493 deleted successfully.
Row 1494 deleted successfully.
Row 1610 deleted successfully.
Row 1640 deleted successfully.
Row 1785 deleted successfully.
Row 1902 deleted successfully.
Row 1932 deleted successfully.
Row 2224 deleted successfully.
Row 2272 deleted successfully.
Row 2486 deleted successfully.
Row 2516 deleted successfully.
Row 2576 deleted successfully.
Row 2585 deleted successfully.
Row 2590 deleted successfully.
Row 2662 deleted successfully.
Row 2778 deleted successfully.
Row 2924 deleted successfully.
Row 2954 deleted successfully.
Row 3245 deleted successfully.
Row 3246 deleted successfully.
Row 3391 deleted successfully.
Row 3537 deleted successfully.
Row 3654 deleted successfully.
Row 3683 deleted successfully.
Row 3684 deleted successfully.
Row 3743 deleted successfully.
Row 3753 deleted successfully.
Row 3829 deleted successfully.
Row 3830 deleted successfully.
Row 3975 deleted successfully.
Row 4238 deleted successfully.
Row 4267 deleted successfully.
Row 4384 deleted successfully.
Row 4413 deleted successfully.
Row 4414 deleted successfully.
Row 4462 deleted successfully.
Row 4535 deleted successfully.
File updated successfully.